"""Triage phase — evaluate find-labeled issues and route them."""

from __future__ import annotations

import asyncio
import logging

from config import HydraFlowConfig
from events import EventBus, EventType, HydraFlowEvent
from issue_store import IssueStore
from pr_manager import PRManager
from state import StateTracker
from triage import TriageRunner

logger = logging.getLogger("hydraflow.triage_phase")


class TriagePhase:
    """Evaluates ``find_label`` issues and routes them to plan or HITL."""

    def __init__(
        self,
        config: HydraFlowConfig,
        state: StateTracker,
        store: IssueStore,
        triage: TriageRunner,
        prs: PRManager,
        event_bus: EventBus,
        stop_event: asyncio.Event,
    ) -> None:
        self._config = config
        self._state = state
        self._store = store
        self._triage = triage
        self._prs = prs
        self._bus = event_bus
        self._stop_event = stop_event

    async def triage_issues(self) -> None:
        """Evaluate ``find_label`` issues and route them.

        Issues with enough context go to ``planner_label`` (planning).
        Issues lacking detail are escalated to ``hitl_label`` with a
        comment explaining what is missing so the dashboard surfaces
        them as "needs attention".
        """
        if not self._config.find_label:
            return

        issues = self._store.get_triageable(self._config.batch_size)
        if not issues:
            return

        logger.info("Triaging %d found issues", len(issues))
        for issue in issues:
            if self._stop_event.is_set():
                logger.info("Stop requested — aborting triage loop")
                return

            self._store.mark_active(issue.number, "find")
            try:
                result = await self._triage.evaluate(issue)

                if self._config.dry_run:
                    continue

                if result.ready:
                    await self._prs.swap_pipeline_labels(
                        issue.number, self._config.planner_label[0]
                    )
                    logger.info(
                        "Issue #%d triaged → %s (ready for planning)",
                        issue.number,
                        self._config.planner_label[0],
                    )
                else:
                    self._state.set_hitl_origin(
                        issue.number, self._config.find_label[0]
                    )
                    self._state.set_hitl_cause(
                        issue.number,
                        "Insufficient issue detail for triage",
                    )
                    self._state.record_hitl_escalation()
                    await self._prs.swap_pipeline_labels(
                        issue.number, self._config.hitl_label[0]
                    )
                    note = (
                        "## Needs More Information\n\n"
                        "This issue was picked up by HydraFlow but doesn't have "
                        "enough detail to begin planning.\n\n"
                        "**Missing:**\n"
                        + "\n".join(f"- {r}" for r in result.reasons)
                        + "\n\n"
                        "Please update the issue with more context and re-apply "
                        f"the `{self._config.find_label[0]}` label when ready.\n\n"
                        "---\n*Generated by HydraFlow Triage*"
                    )
                    await self._prs.post_comment(issue.number, note)
                    await self._bus.publish(
                        HydraFlowEvent(
                            type=EventType.HITL_UPDATE,
                            data={
                                "issue": issue.number,
                                "action": "escalated",
                            },
                        )
                    )
                    logger.info(
                        "Issue #%d triaged → %s (needs attention: %s)",
                        issue.number,
                        self._config.hitl_label[0],
                        "; ".join(result.reasons),
                    )
            finally:
                self._store.mark_complete(issue.number)
