"""HITL phase — process human-in-the-loop corrections."""

from __future__ import annotations

import asyncio
import logging
from collections.abc import Callable

from config import HydraFlowConfig
from events import EventBus, EventType, HydraFlowEvent
from hitl_runner import HITLRunner
from issue_fetcher import IssueFetcher
from issue_store import IssueStore
from phase_utils import safe_file_memory_suggestion
from pr_manager import PRManager
from state import StateTracker
from subprocess_util import AuthenticationError, CreditExhaustedError
from workspace import WorkspaceManager

logger = logging.getLogger("hydraflow.hitl_phase")

_HITL_ORIGIN_DISPLAY: dict[str, str] = {
    "hydraflow-find": "from triage",
    "hydraflow-plan": "from plan",
    "hydraflow-ready": "from implement",
    "hydraflow-review": "from review",
}


class HITLPhase:
    """Processes HITL corrections submitted via the dashboard."""

    def __init__(
        self,
        config: HydraFlowConfig,
        state: StateTracker,
        store: IssueStore,
        fetcher: IssueFetcher,
        worktrees: WorkspaceManager,
        hitl_runner: HITLRunner,
        prs: PRManager,
        event_bus: EventBus,
        stop_event: asyncio.Event,
        active_issues_cb: Callable[[], None] | None = None,
    ) -> None:
        self._config = config
        self._state = state
        self._store = store
        self._fetcher = fetcher
        self._worktrees = worktrees
        self._hitl_runner = hitl_runner
        self._prs = prs
        self._bus = event_bus
        self._stop_event = stop_event
        self._active_issues_cb = active_issues_cb
        # HITL corrections: {issue_number: correction_text}
        self._hitl_corrections: dict[int, str] = {}
        # In-memory tracking of active HITL issues
        self._active_hitl_issues: set[int] = set()
        # Issues that have already had an auto-fix attempt
        self._auto_fix_attempted: set[int] = set()

    @property
    def active_hitl_issues(self) -> set[int]:
        """Return the set of currently active HITL issues."""
        return self._active_hitl_issues

    @property
    def hitl_corrections(self) -> dict[int, str]:
        """Return the pending HITL corrections dict."""
        return self._hitl_corrections

    def submit_correction(self, issue_number: int, correction: str) -> None:
        """Store a correction for a HITL issue to guide retry."""
        self._hitl_corrections[issue_number] = correction

    def skip_issue(self, issue_number: int) -> None:
        """Remove an issue from HITL tracking."""
        self._hitl_corrections.pop(issue_number, None)

    def get_status(self, issue_number: int) -> str:
        """Return the HITL status for an issue.

        Returns ``"processing"`` for actively-running issues, ``"approval"``
        for memory suggestions awaiting human review, a human-readable origin
        label (e.g. ``"from review"``) for escalated items, or ``"pending"``
        when no origin data is available.
        """
        if (
            self._store.is_active(issue_number)
            or issue_number in self._active_hitl_issues
        ):
            return "processing"
        origin = self._state.get_hitl_origin(issue_number)
        if origin:
            if origin in self._config.improve_label:
                return "approval"
            return _HITL_ORIGIN_DISPLAY.get(origin, "pending")
        return "pending"

    async def attempt_auto_fixes(self, hitl_issues: list) -> None:
        """Auto-attempt fixes for newly escalated HITL issues.

        For each issue that hasn't been auto-attempted yet, spin up the
        HITL runner using the escalation cause as guidance.  If the fix
        succeeds, the issue returns to the pipeline without human input.
        """
        for issue in hitl_issues:
            if self._stop_event.is_set():
                break
            issue_number = issue.number if hasattr(issue, "number") else issue.id
            if issue_number in self._auto_fix_attempted:
                continue
            if issue_number in self._active_hitl_issues:
                continue
            if issue_number in self._hitl_corrections:
                continue

            cause = self._state.get_hitl_cause(issue_number)
            if not cause:
                continue

            self._auto_fix_attempted.add(issue_number)
            logger.info(
                "Issue #%d: attempting auto-fix before human correction",
                issue_number,
            )

            # Swap label so the issue leaves the HITL dashboard immediately
            await self._prs.swap_pipeline_labels(
                issue_number, self._config.hitl_autofix_label[0]
            )

            await self._prs.post_comment(
                issue_number,
                "**Auto-fix attempt** — trying automated correction "
                "before requiring human input.\n\n"
                "---\n*Generated by HydraFlow HITL*",
            )

            correction = (
                f"AUTOMATIC FIX ATTEMPT: No human correction has been provided yet. "
                f"Use the escalation cause below as your guide to fix the issue.\n\n"
                f"Escalation cause: {cause}"
            )
            self._hitl_corrections[issue_number] = correction

    async def process_corrections(self) -> None:
        """Process all pending HITL corrections."""
        if not self._hitl_corrections:
            return

        semaphore = asyncio.Semaphore(self._config.max_hitl_workers)

        # Snapshot and clear pending corrections to avoid re-processing
        pending = dict(self._hitl_corrections)
        for issue_number in pending:
            self._hitl_corrections.pop(issue_number, None)

        tasks = [
            asyncio.create_task(
                self._process_one_hitl(issue_number, correction, semaphore)
            )
            for issue_number, correction in pending.items()
        ]

        for task in asyncio.as_completed(tasks):
            await task
            if self._stop_event.is_set():
                for t in tasks:
                    t.cancel()
                await asyncio.gather(*tasks, return_exceptions=True)
                break

    async def _process_one_hitl(
        self,
        issue_number: int,
        correction: str,
        semaphore: asyncio.Semaphore,
    ) -> None:
        """Process a single HITL correction for *issue_number*."""
        async with semaphore:
            if self._stop_event.is_set():
                return

            self._active_hitl_issues.add(issue_number)
            self._notify_active_issues()
            try:
                issue = await self._fetcher.fetch_issue_by_number(issue_number)
                if not issue:
                    logger.warning(
                        "Could not fetch issue #%d for HITL correction",
                        issue_number,
                    )
                    return

                cause = self._state.get_hitl_cause(issue_number) or "Unknown escalation"
                origin = self._state.get_hitl_origin(issue_number)

                # Get or create worktree
                branch = self._config.branch_for_issue(issue_number)
                wt_path = self._config.worktree_path_for_issue(issue_number)
                if not wt_path.is_dir():
                    wt_path = await self._worktrees.create(issue_number, branch)
                self._state.set_worktree(issue_number, str(wt_path))

                # Swap to active label
                await self._prs.swap_pipeline_labels(
                    issue_number, self._config.hitl_active_label[0]
                )

                result = await self._hitl_runner.run(issue, correction, cause, wt_path)

                # File memory suggestion if present in transcript
                if result.transcript:
                    await safe_file_memory_suggestion(
                        result.transcript,
                        "hitl",
                        f"issue #{issue_number}",
                        self._config,
                        self._prs,
                        self._state,
                    )

                if result.success:
                    await self._prs.push_branch(wt_path, branch)

                    if origin and origin in self._config.improve_label:
                        # Improve issues go to triage for implementation
                        target_label = (
                            self._config.find_label[0]
                            if self._config.find_label
                            else None
                        )
                        target_stage = target_label or "pipeline"
                    elif origin:
                        target_label = origin
                        target_stage = origin
                    else:
                        target_label = None
                        target_stage = "pipeline"

                    if target_label:
                        await self._prs.swap_pipeline_labels(issue_number, target_label)
                    else:
                        # No target label — just remove active
                        for lbl in self._config.hitl_active_label:
                            await self._prs.remove_label(issue_number, lbl)

                    self._state.remove_hitl_origin(issue_number)
                    self._state.remove_hitl_cause(issue_number)
                    self._state.remove_hitl_visual_evidence(issue_number)
                    self._state.reset_issue_attempts(issue_number)

                    await self._prs.post_comment(
                        issue_number,
                        f"**HITL correction applied successfully.**\n\n"
                        f"Returning issue to `{target_stage}` stage."
                        f"\n\n---\n*Applied by HydraFlow HITL*",
                    )
                    await self._bus.publish(
                        HydraFlowEvent(
                            type=EventType.HITL_UPDATE,
                            data={
                                "issue": issue_number,
                                "action": "resolved",
                                "status": "resolved",
                            },
                        )
                    )
                    logger.info(
                        "HITL correction succeeded for issue #%d — returning to %s",
                        issue_number,
                        origin,
                    )
                else:
                    await self._prs.swap_pipeline_labels(
                        issue_number, self._config.hitl_label[0]
                    )
                    await self._prs.post_comment(
                        issue_number,
                        f"**HITL correction failed.**\n\n"
                        f"Error: {result.error or 'No details available'}"
                        f"\n\nPlease retry with different guidance."
                        f"\n\n---\n*Applied by HydraFlow HITL*",
                    )
                    await self._bus.publish(
                        HydraFlowEvent(
                            type=EventType.HITL_UPDATE,
                            data={
                                "issue": issue_number,
                                "action": "failed",
                                "status": "pending",
                            },
                        )
                    )
                    logger.warning(
                        "HITL correction failed for issue #%d: %s",
                        issue_number,
                        result.error,
                    )

                # Clean up worktree on success; keep on failure for retry
                if result.success:
                    try:
                        await self._worktrees.destroy(issue_number)
                        self._state.remove_worktree(issue_number)
                    except RuntimeError as exc:
                        logger.warning(
                            "Could not destroy worktree for issue #%d: %s",
                            issue_number,
                            exc,
                        )
            except (AuthenticationError, CreditExhaustedError, MemoryError):
                raise
            except Exception:
                logger.exception("HITL processing failed for issue #%d", issue_number)
            finally:
                self._active_hitl_issues.discard(issue_number)
                self._notify_active_issues()

    def _notify_active_issues(self) -> None:
        """Call the active issues callback if registered."""
        if self._active_issues_cb is not None:
            self._active_issues_cb()
